// Investing term flashcards for spaced-repetition practice
export const FLASHCARD_TERMS = [
  {
    term: "Stock",
    definition: "A share of ownership in a company. When you buy a stock, you own a small piece of that company.",
    example: "If Apple has 16 billion shares and you buy 1 share, you own 1/16-billionth of Apple.",
    category: "Basics",
    emoji: "📈",
  },
  {
    term: "Dividend",
    definition: "A portion of a company's profits paid to shareholders, usually quarterly. Not all companies pay dividends.",
    example: "Coca-Cola pays about £0.46 per share per year — if you own 100 shares, you get £46.",
    category: "Income",
    emoji: "💰",
  },
  {
    term: "Bull Market",
    definition: "A market where stock prices are rising or expected to rise. Named after how a bull attacks — horns upward.",
    example: "The S&P 500 rose 26% in 2023 — that was a bull market year.",
    category: "Market",
    emoji: "🐂",
  },
  {
    term: "Bear Market",
    definition: "A market where prices fall 20% or more from recent highs. Named after how a bear attacks — paws downward.",
    example: "In 2022, the S&P 500 dropped 25%, entering a bear market.",
    category: "Market",
    emoji: "🐻",
  },
  {
    term: "ETF",
    definition: "Exchange-Traded Fund — a basket of stocks you can buy as one unit. It trades like a stock but gives you instant diversification.",
    example: "VUKE tracks the FTSE 100 — buying one share gives you exposure to the UK's 100 biggest companies.",
    category: "Funds",
    emoji: "🧺",
  },
  {
    term: "Market Cap",
    definition: "The total value of a company's shares. Calculated as share price × number of outstanding shares.",
    example: "Microsoft at $420/share with 7.4 billion shares = $3.1 trillion market cap.",
    category: "Valuation",
    emoji: "🏷️",
  },
  {
    term: "P/E Ratio",
    definition: "Price-to-Earnings ratio — how much you pay per £1 of company profit. A lower P/E can mean a cheaper stock, but not always.",
    example: "A stock at £100 earning £5/share has a P/E of 20 — you pay £20 for every £1 of earnings.",
    category: "Valuation",
    emoji: "⚖️",
  },
  {
    term: "Diversification",
    definition: "Spreading your money across different stocks, sectors, and asset types to reduce risk.",
    example: "Owning shares in tech, healthcare, energy, and food means one sector crashing won't wipe you out.",
    category: "Strategy",
    emoji: "🌈",
  },
  {
    term: "Compound Interest",
    definition: "Earning interest on your interest. Your returns generate more returns, creating exponential growth over time.",
    example: "£1,000 growing 10%/year becomes £2,594 in 10 years and £6,727 in 20 years — without adding a penny.",
    category: "Strategy",
    emoji: "🌀",
  },
  {
    term: "IPO",
    definition: "Initial Public Offering — when a private company first sells shares to the public. Also called 'going public'.",
    example: "Facebook's IPO in 2012 raised $16 billion at $38/share.",
    category: "Market",
    emoji: "🚀",
  },
  {
    term: "Portfolio",
    definition: "The full collection of investments you own — stocks, bonds, ETFs, cash, and other assets.",
    example: "A £10,000 portfolio might hold 5 stocks, 2 ETFs, and £1,000 in cash.",
    category: "Strategy",
    emoji: "📁",
  },
  {
    term: "Blue Chip Stock",
    definition: "Shares of large, well-established, financially stable companies with a history of reliable performance.",
    example: "Apple, Microsoft, and Unilever are considered blue chip stocks.",
    category: "Stocks",
    emoji: "🔵",
  },
  {
    term: "Growth Stock",
    definition: "A company expected to grow sales and profits faster than the market average. Usually doesn't pay dividends.",
    example: "Nvidia and Tesla are growth stocks — they reinvest profits instead of paying dividends.",
    category: "Stocks",
    emoji: "🌱",
  },
  {
    term: "Value Stock",
    definition: "A stock that appears undervalued — trading below what its fundamentals suggest it's worth.",
    example: "A bank trading at a P/E of 6 when the sector average is 12 might be a value stock.",
    category: "Stocks",
    emoji: "💎",
  },
  {
    term: "Volatility",
    definition: "How much a stock's price swings up and down. Higher volatility means bigger price moves, both up and down.",
    example: "Bitcoin has high volatility — it can swing 10% in a day. Government bonds have low volatility.",
    category: "Risk",
    emoji: "🎢",
  },
  {
    term: "Dollar-Cost Averaging",
    definition: "Investing a fixed amount at regular intervals, regardless of price. You buy more shares when prices are low and fewer when high.",
    example: "Investing £100/month every month — you buy more shares when the market is down, fewer when it's up.",
    category: "Strategy",
    emoji: "📅",
  },
  {
    term: "Limit Order",
    definition: "An order to buy or sell a stock only at a specific price or better. You set the maximum price you'll pay or minimum you'll accept.",
    example: "A limit order to buy Apple at £150 means it won't execute until the price drops to £150 or below.",
    category: "Trading",
    emoji: "🎯",
  },
  {
    term: "Market Order",
    definition: "An order to buy or sell a stock immediately at the best available current price. Fastest but no price guarantee.",
    example: "A market order to buy Tesla executes instantly at whatever the current price is.",
    category: "Trading",
    emoji: "⚡",
  },
  {
    term: "Stop-Loss Order",
    definition: "An order that automatically sells a stock when it drops to a specific price, limiting your losses.",
    example: "Set a stop-loss at £90 on a £100 stock — if it drops to £90, it auto-sells to prevent further loss.",
    category: "Trading",
    emoji: "🛑",
  },
  {
    term: "Yield",
    definition: "The annual income from a dividend-paying stock, expressed as a percentage of the share price.",
    example: "A £100 stock paying £4/year in dividends has a 4% yield.",
    category: "Income",
    emoji: "📊",
  },
  {
    term: "Liquidity",
    definition: "How easily an asset can be bought or sold without affecting its price. Cash is highly liquid; property is not.",
    example: "Large stocks like Apple are very liquid — you can sell £10,000 worth instantly without moving the price.",
    category: "Risk",
    emoji: "💧",
  },
  {
    term: "EPS",
    definition: "Earnings Per Share — a company's profit divided by its number of shares. Higher EPS means more profit per share.",
    example: "A company earning £10 million with 5 million shares has an EPS of £2.00.",
    category: "Valuation",
    emoji: "🧮",
  },
  {
    term: "Capital Gain",
    definition: "The profit you make when you sell an asset for more than you paid for it.",
    example: "Buy a stock at £50, sell at £75 — your capital gain is £25 per share.",
    category: "Income",
    emoji: "🎯",
  },
  {
    term: "Index Fund",
    definition: "A fund that tracks a specific market index, like the S&P 500 or FTSE 100. You get the market's average return at low cost.",
    example: "A S&P 500 index fund rises when the 500 largest US companies rise, on average.",
    category: "Funds",
    emoji: "📋",
  },
  {
    term: "Sector",
    definition: "A group of companies in the same industry. Major sectors include tech, healthcare, finance, energy, and consumer goods.",
    example: "Apple, Microsoft, and Google are in the technology sector. BP and Shell are in the energy sector.",
    category: "Basics",
    emoji: "🏭",
  },
  {
    term: "Brokerage",
    definition: "A platform or service that lets you buy and sell stocks. They act as the middleman between you and the stock exchange.",
    example: "Trading212, Hargreaves Lansdown, and eToro are popular UK brokerages.",
    category: "Basics",
    emoji: "🏦",
  },
  {
    term: "Ticker",
    definition: "The short abbreviation used to identify a stock on an exchange. Usually 1-5 letters.",
    example: "AAPL is Apple's ticker. TSLA is Tesla's. SHEL is Shell's.",
    category: "Basics",
    emoji: "🔤",
  },
  {
    term: "ROE",
    definition: "Return on Equity — how efficiently a company uses shareholders' money to generate profit. Higher is generally better.",
    example: "A company with £100M equity generating £20M profit has an ROE of 20%.",
    category: "Valuation",
    emoji: "🔄",
  },
  {
    term: "Diversified Portfolio",
    definition: "A portfolio spread across multiple stocks, sectors, and asset types so no single investment dominates your risk.",
    example: "Owning 15 stocks across 5 sectors, plus 2 ETFs, is more diversified than holding 3 tech stocks.",
    category: "Strategy",
    emoji: "🧩",
  },
  {
    term: "Inflation",
    definition: "The rate at which prices rise, reducing the purchasing power of money. In the UK, the target is around 2% per year.",
    example: "If inflation is 5%, £100 today buys what £95 bought a year ago.",
    category: "Economics",
    emoji: "🌡️",
  },
];